version: 0.0
os: linux
files:
- source: /
  destination: /var/www/platform

permissions:
- object: /
  pattern: "**"
  owner: ec2-user
  group: ec2-user
- object: /var/www/platform/bin
  mode: 755
  type: file

hooks:
ApplicationStop:
   - location: /var/www/platform/bin/stop
     timeout: 10
     runas: ec2-user

AfterInstall:
   - location: /var/www/platform/bin/install-dependencies
     timeout: 1200
     runas: ec2-user

ApplicationStart:
   - location: /var/www/platform/bin/start
     timeout: 60
     runas: ec2-user