version: 0.0
os: linux
files:
- source: /
  destination: /var/www/platform

permissions:
- object: /
  pattern: "**"
  owner: ec2-user
  group: ec2-user
#- object: /var/www/platform/bin
#  pattern: "*.sh"
#  mode: 755
#  type:
#    - file

hooks:
ApplicationStop:
   - location: bin/stop.sh
     timeout: 10
     runas: ec2-user

AfterInstall:
   - location: bin/install-dependencies.sh
     timeout: 1200
     runas: ec2-user

ApplicationStart:
   - location: bin/start.sh
     timeout: 60
     runas: ec2-user