version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm update
      - npm install -g typescript
  build:
    commands:
      - echo Build started
      - echo Compiling the Node.js code
      - npm install
      - tsc || true
      - echo Compiled Typescript code
  post_build:
    commands:
      - echo Build completed
      - chmod -R +x bin/*.sh
      - echo Cleaning old typescript files
      - rm -r *.ts
      - echo Finished!
artifacts:
  files:
    - appspec.yml
    - bin/**/*
    - models/**/*
    - node_modules/**/*
    - public/*
    - routes/*
    - routes/**/*
    - views/*
    - views/**/*
    - app.js
    - db/*